/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samplegui;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PRATHAMESH
 */
public class EditGroup extends javax.swing.JFrame {

    /**
     * Creates new form EditGroup
     */
    public EditGroup() {
        initComponents();
        this.setSize(761,520);
        this.setVisible(true);
        this.setTitle("Projob :: Edit Group");
        try{
            Image image = new ImageIcon("Images\\icon.png").getImage();
            this.setIconImage(image);
            }catch(Exception e){
            System.out.println("Appilcation icon not found");
        }
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocation(357,150);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        con();
        retData();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Simplifica", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit Group");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 10, 144, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Group ID", "Group Name", "Group Leader", "Group Member 1", "Group Member 2", "Branch", "Group Guide", "project approved"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 59, 740, 209);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 420, 134, 42);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Group Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 290, 100, 30);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 420, 143, 42);

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 290, 150, 30);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(102, 102, 102));
        jTextField2.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 330, 130, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(102, 102, 102));
        jTextField3.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(230, 370, 130, 30);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(102, 102, 102));
        jTextField4.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(600, 290, 130, 30);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(102, 102, 102));
        jTextField5.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(600, 370, 130, 30);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Group Leader :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 330, 100, 30);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Group Member 1 :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 370, 110, 30);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Group Member 2 :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 290, 120, 30);

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Branch :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 330, 80, 30);

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Group Guide :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 370, 100, 30);

        jComboBox1.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox1.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INFT", "CMPN", "EXTC", "ETRX" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(520, 330, 150, 30);

        jComboBox2.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox2.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(150, 330, 60, 30);

        jComboBox3.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox3.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(150, 370, 60, 30);

        jComboBox4.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox4.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(520, 290, 60, 30);

        jComboBox5.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox5.setFont(new java.awt.Font("Simplifica", 1, 18)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(520, 370, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/samplegui/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-260, 0, 1230, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // delete
        String[] options={"Yes","No"};
        int ans=JOptionPane.showOptionDialog(this, "Are you sure to delete this entry?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,null,options,options[1]);
        
        if(ans==0){
            int index=jTable1.getSelectedRow();
            String id=jTable1.getValueAt(index, 0).toString();
            if(delData(id)){
                
                retData();
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jComboBox2.setSelectedIndex(-1);
                jComboBox3.setSelectedIndex(-1);
                jComboBox4.setSelectedIndex(-1);
                jComboBox5.setSelectedIndex(-1);
                JOptionPane.showMessageDialog(this, "Deleted the selected record successfully.");
            }
            else{
                JOptionPane.showMessageDialog(this, "Error!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public Boolean delData(String id){
        String sql="Delete from groupdata where groupid='"+id+"'";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projob","root","root");  
            Statement s=con.prepareStatement(sql);
            System.out.println(id);
            s.execute(sql);
            System.out.println(id);
            return true;
        }
        catch(Exception e){
            e.printStackTrace();
            return false;
        }
    }
    
    public void retData(){
        DefaultTableModel dm=new DefaultTableModel();
        dm.addColumn("Group ID");
        dm.addColumn("Group Name");
        dm.addColumn("Group Leader");
        dm.addColumn("Group Member 1");
        dm.addColumn("Group Member 2");
        dm.addColumn("Branch");
        dm.addColumn("Group Guide");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projob","root","root");                
		String sql = "select * from groupdata";
                // execute insert SQL stetement
                Statement s=con.prepareStatement(sql);
                ResultSet rs=s.executeQuery(sql);
                while(rs.next()){
                    String groupid=rs.getString(1);
                    String groupname=rs.getString(2);
                    String groupleader=rs.getString(3);
                    String groupmem1=rs.getString(4);
                    String groupmem2=rs.getString(5);
                    String branch=rs.getString(6);
                    String guidename=rs.getString(7);
                    
                    //System.out.println(id+"\t"+name);
                    dm.addRow(new String[]{groupid,groupname,groupleader,groupmem1,groupmem2,branch,guidename});
                }

                jTable1.setModel(dm);
		//System.out.println("Record is inserted into DBUSER table!");        
        }
        catch(ClassNotFoundException | SQLException e){}
    }
    
    public Boolean updateData(String id, String groupname,String groupleader,String groupmem1,String groupmem2,String branch,String guidename){
        String sql="update groupdata set groupname='"+groupname+"', leader='"+groupleader+"', "+ "mem1='"+groupmem1+"', mem2='"+groupmem2+"', branch='"+branch+"', "+ "guide='"+guidename+"' where groupid="+id;
        try{ 
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projob","root","root");
            
            Statement s=con.prepareStatement(sql);
            s.execute(sql);
            return true;
        }
        catch(ClassNotFoundException | SQLException e){
            return false;
        }
    }
 
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String groupname=jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String groupleader=jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String groupmem1=jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String groupmem2=jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String branch=jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString();
        String guidename=jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
               
        System.out.println(groupname+"\n"+groupleader+"\n"+groupmem1+"\n"+groupmem2+"\n"+branch+"\n"+guidename);
               
        jTextField1.setText(groupname);
        jTextField2.setText(groupleader);
        jTextField3.setText(groupmem1);
        jTextField4.setText(groupmem2);
        jComboBox1.setSelectedItem(branch);
        jTextField5.setText(guidename);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //update
        int index=jTable1.getSelectedRow();
        String id=jTable1.getValueAt(index, 0).toString();
        System.out.println(id);
        if(updateData(id,jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),(String)jComboBox1.getSelectedItem(),jTextField5.getText())){
            retData();
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            
            JOptionPane.showMessageDialog(this, "Records Updated");
        }
        else{
            JOptionPane.showMessageDialog(this, "Error!");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        refreshCombo();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        refreshCombo();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        refreshCombo();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        refreshCombo();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    public void con(){
        
        try{ 
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projob","root","root");
                //here sonoo is database name, root is username and password
                Statement stmt=con.createStatement();
                //combobox for groupguide
                String sql = "SELECT guideid FROM guide";
                ResultSet rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    String name  = rs.getString("guideid");  
                    System.out.println(name);
                    jComboBox5.addItem(rs.getString("guideid"));
                }
                
                sql="SELECT rollno from student";
                rs=stmt.executeQuery(sql);
                while(rs.next()){
                    String roll=rs.getString("rollno");
                    jComboBox2.addItem(roll);
                    jComboBox3.addItem(roll);
                    jComboBox4.addItem(roll);
                }
                
        }               
        catch(Exception z)
        {      
        }
        
             
    }
    
    public void refreshCombo(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projob","root","root");
                //here sonoo is database name, root is username and password
                Statement stmt=con.createStatement();
                //combobox for leader
                String roll=(String)jComboBox2.getSelectedItem();
                String sql = "SELECT name FROM student WHERE rollno="+roll;
                System.out.println(roll);
                ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                String name=rs.getString("name");
                System.out.println(name);
                jTextField2.setText(name);
                }
                
                //combobox for mem1
                roll=(String)jComboBox3.getSelectedItem();
                sql = "SELECT name FROM student WHERE rollno="+roll;
                System.out.println(roll);
                rs = stmt.executeQuery(sql);
                while(rs.next()){
                String name=rs.getString("name");
                System.out.println(name);
                jTextField3.setText(name);
                }
                
                //combobox for mem2
                roll=(String)jComboBox4.getSelectedItem();
                sql = "SELECT name FROM student WHERE rollno="+roll;
                System.out.println(roll);
                rs = stmt.executeQuery(sql);
                while(rs.next()){
                String name=rs.getString("name");
                System.out.println(name);
                jTextField4.setText(name);
                }
                
                //combobox for guidename
                String id=(String)jComboBox5.getSelectedItem();
                sql = "SELECT guidename FROM guide WHERE guideid="+id;
                System.out.println(roll);
                rs = stmt.executeQuery(sql);
                while(rs.next()){
                String name=rs.getString("guidename");
                System.out.println(name);
                jTextField5.setText(name);
                }
        }
        catch(Exception e){
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
